print("#StudentForm \n\n")
print("Welcome User! \n\n")
name = input("Enter your name: ")
print(f"\n\nHello {name}! Please fill in your details below: ")
age = input("\n\nEnter your age: ")
no = input("\nEnter your mobile number: ")
email = input("\nEnter your Email ID: ")
degree = input("\nEnter your graduation degree: ")
uni = input("\nEnter your university: ")
cgpa = input("\nEnter your CGPA: ")
print("\n\nThanks! Please check your details below: \n")
print(f"You are {name}, a {age} year old student studying {degree} at {uni} with {cgpa} CGPA! \n")
print(f"Your mobile number is: {no} & Email ID is: {email}! \n")
print("\nThank You!")